import Head from 'next/head';
import Image from 'next/image';
import { fetchProducts } from '../services/fetchProducts';
import { TProduct } from '../utils/types';
import Link from 'next/link';

export async function getServerSideProps() {
  const products = await fetchProducts();

  return { props: { products: products || [] } };
}

export default function Home({ products }: { products: TProduct[] }) {
  if (products) console.log(products);
  return (
    <>
      <Head>
        <title>Product page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {products.map(({ id, title, body_html, image }: TProduct) => (
            <div key={id}>
              <Link href={`/product/${id}`}>
                <Image
                  src={image.src.split('?')[0]}
                  alt={title}
                  width={650}
                  height={650}
                />
                <h2>{title}</h2>
              </Link>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
