import Head from 'next/head';
import { fetchProducts } from '../services/fetchProducts';
import { TProduct } from '../utils/types';
import ProductGrid from '../components/ProductsGrid/ProductsGrid';
import { Main } from './index.styled';

export async function getServerSideProps() {
  const products = await fetchProducts();

  return { props: { products: products || [] } };
}

export default function Home({ products }: { products: TProduct[] }) {
  if (products) console.log(products);
  return (
    <>
      <Head>
        <title>Product page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <ProductGrid products={products} />
      </Main>
    </>
  );
}
